#pragma once

#define USE_NAMESPACE_SHARE using namespace SHARE;
#define USE_NAMESPACE_SHARE_MULTI(NAME) using namespace SHARE::NAME;
#define START_SHARE_NAMESPACE namespace SHARE {
#define START_SHARE_NAMESPACE_MULTI(NAME) namespace SHARE::NAME {
#define END_SHARE_NAMESPACE }

#define USE_NAMESPACE_TRADEUP_ENGINE using namespace TRADEUP_ENGINE;
#define USE_NAMESPACE_TRADEUP_ENGINE_MULTI(NAME) using namespace TRADEUP_ENGINE::NAME;
#define START_ENGINE_NAMESPACE namespace TRADEUP_ENGINE {
#define START_ENGINE_NAMESPACE_MULTI(NAME) namespace TRADEUP_ENGINE::NAME {
#define END_ENGINE_NAMESPACE }
